import { AdvancedFilterInput, BaseRelationValuesInput, BulkOperationCsvExportKeys, Collection, DropdownOption, EntitiesResults, Entity, EntityInput, Entitytyping, FilterMatcherMap, GraphElementInput, Maybe, MediaFileInput, MediaFileMetadataInput, Metadata, MetadataFieldInput, MetadataValuesInput, SearchFilter, PermissionRequestInfo, DeleteEntitiesInput } from '../../../generated-types/type-defs';
import { AuthRESTDataSource } from '../auth/AuthRESTDataSource';
import { Config } from '../types';
export declare class CollectionAPI extends AuthRESTDataSource {
    baseURL: string;
    config: Config | 'no-config';
    preferredLanguage: string;
    getSessionInfo(key: string): Promise<string>;
    getFilterMatcherMapping(): Promise<FilterMatcherMap>;
    getUserPermissions(): Promise<{
        payload: string[];
    }>;
    getEntities(limit: number, skip: number, searchValue: SearchFilter, type: Entitytyping): Promise<EntitiesResults>;
    getEntitiesByAdvancedSearch(q: string, query_by: string, filter_by: string, query_by_weights?: string, sort_by?: string, limit?: number, per_page?: number, facet_by?: string): Promise<EntitiesResults>;
    getTenants(): Promise<EntitiesResults>;
    getEntitiesByType(entityType: string): Promise<Entity[]>;
    checkAdvancedPermission(permissionRequestInfo: PermissionRequestInfo, parentEntityId: Maybe<string> | undefined, childEntityId: Maybe<string> | undefined): Promise<boolean>;
    postEntitiesFilterSoftCall(entityType: string): Promise<string>;
    postEntitySoftCall(entityType: string): Promise<string>;
    patchEntityDetailSoftCall(id: String, entityType: string, collection?: Collection): Promise<string>;
    delEntityDetailSoftCall(id: String, entityType: string, collection?: Collection): Promise<string>;
    getEntity(id: string, type: string, _collection?: string | undefined, returnIdIfFails?: boolean): Promise<any>;
    getEntityById(id: string): Promise<any>;
    getNewObjectId(): Promise<string>;
    setMediaPrimaire(entity_id: string, mediafile_id: string): Promise<any>;
    setThumbnailPrimaire(entity_id: string, mediafile_id: string): Promise<any>;
    getMediafiles(id: string): Promise<any>;
    addRelations(id: string, relations: any[]): Promise<any[]>;
    getRelations(entityId: string, collection?: Collection): Promise<Metadata[]>;
    getMediaFile(mediaFileId: String): Promise<any>;
    getAssetsRelationedWithMediafFile(mediaFileId: String): Promise<any>;
    postMediaFile(mediaFileInput: MediaFileInput): Promise<any>;
    linkMediafileToEntity(entityId: String, mediaFileInput: MediaFileInput): Promise<any>;
    patchMetaDataMediaFile(mediafileId: String, mediaFileMetadata: Maybe<MediaFileMetadataInput>[]): Promise<any>;
    replaceMetadata(id: String, metadata: Maybe<MetadataFieldInput>[]): Promise<Metadata[]>;
    patchMetadata(id: String, metadata: MetadataValuesInput[], collection?: Collection): Promise<Metadata[]>;
    postRelations(id: string, relations: BaseRelationValuesInput[], collection?: Collection): Promise<any[]>;
    patchRelations(id: string, relations: BaseRelationValuesInput[], collection?: Collection): Promise<any[]>;
    deleteRelations(id: string, relations: BaseRelationValuesInput[], collection?: Collection): Promise<any>;
    putRelations(id: string, relations: BaseRelationValuesInput[], collection?: Collection): Promise<any>;
    deleteData(id: string, path: Collection, deleteMediafiles: boolean): Promise<any>;
    bulkDeleteEntities(ids: string[], path: Collection, deleteEntities: DeleteEntitiesInput, skipItemsWithRelationDuringBulkDelete: string[]): Promise<string>;
    createEntity(entity: EntityInput, metadata?: Metadata[], relations?: any[]): Promise<any>;
    getSixthCollectionId(): Promise<string>;
    getConfig(): Promise<Config>;
    getSkip(skip: number, limit: number): number;
    setLabels: (response: any) => void;
    GetAdvancedEntities(type: Entitytyping, limit: number, skip: number, advancedFilterInputs: AdvancedFilterInput[], advancedSearchValue: SearchFilter): Promise<EntitiesResults>;
    private doAdvancedEntitiesCall;
    private doAdvancedHistoryEntitiesCall;
    private doAdvancedMediaCall;
    updateMetadataWithCsv(entityType: string, csv: any): Promise<any>;
    GetCsvExportKeysPerEntityType(entityType: string, requiredKeys?: string[]): Promise<BulkOperationCsvExportKeys>;
    GetFilterOptions(input: AdvancedFilterInput[], limit: number, entityType: string, preferredLanguage?: string | null): Promise<DropdownOption[]>;
    GetStats(id: string, graph: GraphElementInput): Promise<any>;
    getDerivatives(mediafileId: string): Promise<any>;
}
